/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        birinciSayiLabel = new javax.swing.JLabel();
        ikinciSayiLabel = new javax.swing.JLabel();
        sonucLabel = new javax.swing.JLabel();
        HesaplaBtn = new javax.swing.JButton();
        birinciSayiTf = new javax.swing.JTextField();
        ikinciSayiTf = new javax.swing.JTextField();
        toplamaBtn = new javax.swing.JButton();
        cikarmaBtn = new javax.swing.JButton();
        carpmaBtn = new javax.swing.JButton();
        BolmeBtn = new javax.swing.JButton();
        sonucTf = new javax.swing.JTextField();
        sifirlaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        birinciSayiLabel.setText("Birinci Sayı:");

        ikinciSayiLabel.setText("İkinci Sayı:");

        sonucLabel.setText("Sonuç:");

        HesaplaBtn.setText("Hesapla");
        HesaplaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HesaplaBtnActionPerformed(evt);
            }
        });

        birinciSayiTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birinciSayiTfActionPerformed(evt);
            }
        });

        toplamaBtn.setText("Toplama");
        toplamaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toplamaBtnActionPerformed(evt);
            }
        });

        cikarmaBtn.setText("Çıkarma");
        cikarmaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikarmaBtnActionPerformed(evt);
            }
        });

        carpmaBtn.setText("Çarpma");
        carpmaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carpmaBtnActionPerformed(evt);
            }
        });

        BolmeBtn.setText("Bölme");
        BolmeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BolmeBtnActionPerformed(evt);
            }
        });

        sonucTf.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        sonucTf.setEnabled(false);
        sonucTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonucTfActionPerformed(evt);
            }
        });

        sifirlaBtn.setText("Sıfırla");
        sifirlaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifirlaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(birinciSayiLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(birinciSayiTf, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ikinciSayiLabel)
                                    .addComponent(sonucLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ikinciSayiTf)
                                    .addComponent(sonucTf))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HesaplaBtn)
                            .addComponent(sifirlaBtn))
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toplamaBtn)
                        .addGap(28, 28, 28)
                        .addComponent(cikarmaBtn)
                        .addGap(31, 31, 31)
                        .addComponent(carpmaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BolmeBtn)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(HesaplaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sifirlaBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(birinciSayiLabel)
                            .addComponent(birinciSayiTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ikinciSayiLabel)
                            .addComponent(ikinciSayiTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sonucLabel)
                            .addComponent(sonucTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toplamaBtn)
                    .addComponent(cikarmaBtn)
                    .addComponent(carpmaBtn)
                    .addComponent(BolmeBtn))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void birinciSayiTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birinciSayiTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birinciSayiTfActionPerformed

    private void HesaplaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HesaplaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HesaplaBtnActionPerformed

    private void toplamaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toplamaBtnActionPerformed
       int birinciSayi = Integer.parseInt(birinciSayiTf.getText());
       int ikinciSayi = Integer.parseInt(ikinciSayiTf.getText());
       int sonuc = birinciSayi + ikinciSayi;
       sonucTf.setText(Integer.toString(sonuc));
         
    }//GEN-LAST:event_toplamaBtnActionPerformed

    private void cikarmaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikarmaBtnActionPerformed
        int birinciSayi = Integer.parseInt(birinciSayiTf.getText());
        int ikinciSayi = Integer.parseInt(ikinciSayiTf.getText());
        int sonuc = birinciSayi - ikinciSayi;
        sonucTf.setText(Integer.toString(sonuc));
    }//GEN-LAST:event_cikarmaBtnActionPerformed

    private void carpmaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carpmaBtnActionPerformed
        int birinciSayi = Integer.parseInt(birinciSayiTf.getText());
        int ikinciSayi = Integer.parseInt(ikinciSayiTf.getText());
        int sonuc = birinciSayi * ikinciSayi;
        sonucTf.setText(Integer.toString(sonuc));
    }//GEN-LAST:event_carpmaBtnActionPerformed

    private void BolmeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BolmeBtnActionPerformed
        double birinciSayi = Double.parseDouble(birinciSayiTf.getText());
        double ikinciSayi = Double.parseDouble(ikinciSayiTf.getText());
        double sonuc = birinciSayi / ikinciSayi;
        sonucTf.setText(String.valueOf(sonuc));
    }//GEN-LAST:event_BolmeBtnActionPerformed

    private void sonucTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonucTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sonucTfActionPerformed

    private void sifirlaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifirlaBtnActionPerformed
        birinciSayiTf.setText("");
        ikinciSayiTf.setText("");
    }//GEN-LAST:event_sifirlaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BolmeBtn;
    private javax.swing.JButton HesaplaBtn;
    private javax.swing.JLabel birinciSayiLabel;
    private javax.swing.JTextField birinciSayiTf;
    private javax.swing.JButton carpmaBtn;
    private javax.swing.JButton cikarmaBtn;
    private javax.swing.JLabel ikinciSayiLabel;
    private javax.swing.JTextField ikinciSayiTf;
    private javax.swing.JButton sifirlaBtn;
    private javax.swing.JLabel sonucLabel;
    private javax.swing.JTextField sonucTf;
    private javax.swing.JButton toplamaBtn;
    // End of variables declaration//GEN-END:variables
}
